version: '3.8'

services:

  db:
    restart: always
    image: postgres:12
    environment:
      POSTGRES_DB: pricefetch
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./.db-data:/var/lib/postgresql/data
  rabbitmq3:
    image: rabbitmq:3-management
    container_name: rabbitmq
    user: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /

