version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq3
    env_file:
      - ./.env
  celery:
    build: .
    command: celery -A pricefetch worker -l info
    volumes:
      - .:/opt/app
    depends_on:
      - web
      - db
      - rabbitmq3
  celery-beat:
    build: .
    command: celery -A pricefetch beat -l info
    volumes:
      - .:/opt/app
    depends_on:
      - rabbitmq3

  db:
    restart: always
    image: postgres:12
    environment:
      POSTGRES_DB: pricefetch
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - /data:/var/lib/postgresql/data
  rabbitmq3:
    image: rabbitmq:3-management
    container_name: rabbitmq
    user: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /

