# Generated by Django 3.2.8 on 2021-10-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency_code', models.CharField(default='BTC', max_length=50)),
                ('from_currency_name', models.CharField(default='Bitcoin', max_length=50)),
                ('to_currency_code', models.CharField(default='USD', max_length=50)),
                ('to_currency_name', models.CharField(default='United States Dollar', max_length=50)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('last_refreshed', models.DateTimeField()),
                ('time_zone', models.CharField(default='UTC', max_length=10)),
                ('bid_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('ask_price', models.DecimalField(decimal_places=8, max_digits=18)),
            ],
        ),
    ]
